/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package AreaIT;

import CotizadorPlai.Main;
import CotizadorPlai.NuevaCotizacion;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import AreaIT.historialAreaIT;
/**
 *
 * @author brmay
 */
public class CotizacionIT extends javax.swing.JFrame {
    private Main main;
    static float Costo_por_almacenamiento = 580, Costo_de_soporte = 624, Costo_por_gestion = 85;
    static ArrayList<JTextField>ListaText=new ArrayList();

    /**
     * Creates new form CotizacionIT
     */
    public CotizacionIT(NuevaCotizacion nuevaCotizacion,Main main) {
        this.main=main;
        this.jpNuevaCotizacion=nuevaCotizacion.getJpNuevaCotizacion();
        initComponents();
        getContentPane().setBackground(Color.white);
        setSize(600, 570);
        setResizable(false);
        setLocationRelativeTo(null);
        ListaText.add(txtCC);
        ListaText.add(txtOP);
        ListaText.add(txtTA);
        Design();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFranja = new javax.swing.JLabel();
        jpCotizacionIT = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        txtCliente = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        txtOP = new javax.swing.JTextField();
        lblCantidadOP = new javax.swing.JLabel();
        txtCC = new javax.swing.JTextField();
        lblCantidadCursos = new javax.swing.JLabel();
        txtTA = new javax.swing.JTextField();
        lblTiempoAl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(214, 217, 223));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.magenta);
        getContentPane().setLayout(null);
        getContentPane().add(lblFranja);
        lblFranja.setBounds(0, 0, 660, 50);

        jpCotizacionIT.setLayout(null);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jpCotizacionIT.add(btnVolver);
        btnVolver.setBounds(10, 60, 72, 23);
        jpCotizacionIT.add(txtCliente);
        txtCliente.setBounds(180, 140, 210, 30);

        lblCliente.setText("Nombre del cliente:");
        jpCotizacionIT.add(lblCliente);
        lblCliente.setBounds(10, 140, 220, 16);

        lblTitle.setText("Nueva Cotizacion AreaIT");
        jpCotizacionIT.add(lblTitle);
        lblTitle.setBounds(190, 70, 460, 50);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CotizadorPlai/cleaning_9717915.png"))); // NOI18N
        btnLimpiar.setToolTipText("Limpiar campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jpCotizacionIT.add(btnLimpiar);
        btnLimpiar.setBounds(520, 400, 90, 40);

        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CotizadorPlai/accounting_calculator_banking_currency_dollar_bank_business_money_making_icon_258655.png"))); // NOI18N
        btnCalcular.setToolTipText("Cotizar");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jpCotizacionIT.add(btnCalcular);
        btnCalcular.setBounds(210, 400, 90, 40);
        jpCotizacionIT.add(txtOP);
        txtOP.setBounds(380, 280, 116, 30);

        lblCantidadOP.setText(" Cantidad de operadores para brindar el soporte:");
        jpCotizacionIT.add(lblCantidadOP);
        lblCantidadOP.setBounds(10, 290, 559, 16);
        jpCotizacionIT.add(txtCC);
        txtCC.setBounds(190, 230, 110, 30);

        lblCantidadCursos.setText(" Cantidad de Cursos:");
        jpCotizacionIT.add(lblCantidadCursos);
        lblCantidadCursos.setBounds(10, 240, 150, 16);
        jpCotizacionIT.add(txtTA);
        txtTA.setBounds(520, 180, 110, 30);

        lblTiempoAl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTiempoAl.setText("Tiempo de almacenamiento (meses que el curso estará en plataforma):");
        jpCotizacionIT.add(lblTiempoAl);
        lblTiempoAl.setBounds(10, 180, 700, 25);

        getContentPane().add(jpCotizacionIT);
        jpCotizacionIT.setBounds(0, 0, 800, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        try {
            
            int Tiempo_de_almacenamiento = Integer.parseInt(txtTA.getText().trim());
            int Cantidad_de_cursos = Integer.parseInt(txtCC.getText().trim());
            int Cantidad_de_operadores = Integer.parseInt(txtOP.getText().trim());
            String Cliente=txtCliente.getText().trim();
            
            
            if(validarNegativo()){
                JOptionPane.showMessageDialog(null,"No se puede poner numeros negativos","Valor invalido",JOptionPane.ERROR_MESSAGE);
                return;
            }

            float Cotizacion = Tiempo_de_almacenamiento * ((Cantidad_de_cursos * Costo_por_almacenamiento) + ((Cantidad_de_cursos / 30.0f) * Costo_de_soporte)) + (Cantidad_de_operadores * Cantidad_de_cursos * Costo_por_gestion);

            subirInfo(Tiempo_de_almacenamiento, Cantidad_de_cursos, Cantidad_de_operadores, Cotizacion, Cliente);
            AclararCampos();
            JOptionPane.showMessageDialog(this, "La cotización es: " + Cotizacion);
        } catch(NumberFormatException e) {
            if(validarCampoVacio()){
                JOptionPane.showMessageDialog(null,"Tiene que rellenar los campos en rojo.","Campos vacios",JOptionPane.ERROR_MESSAGE);
            }else if(validarCaracter()){
                JOptionPane.showMessageDialog(null,"Los campos tienen que llenarse con numeros enteros. No se permiten caracteres ni numeros con comas","Valor invalido",JOptionPane.ERROR_MESSAGE);
            }        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error de conexion, intente de nuevo","Fail Coneccion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtCC.setText("");
        txtOP.setText("");
        txtTA.setText("");
        AclararCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        jpCotizacionIT.setVisible(false);
        jpNuevaCotizacion.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void subirInfo(int Tiempo_de_almacenamiento, int Cantidad_de_cursos, int Cantidad_de_operadores, float Cotizacion,String Cliente) {
        try {
            String token = generarToken();
            URL url = new URL("http://localhost:8055/items/IT");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("POST");
            con.setRequestProperty("Content-Type", "application/json");
            con.setRequestProperty("Authorization", "Bearer " + token);
            con.setDoOutput(true);

            String jsonInputString = String.format(
                "{\"Nombre\": \"%s\", \"Tiempo_de_almacenamiento\": %d, \"Cantidad_de_cursos\": %d, \"Costo_por_almacenamiento\": %.2f, \"Costo_soporte_tecnico\": %.2f, \"Cantidad_de_operadores\": %d, \"Costo_moodle\": %.2f, \"Cotizacion\": %.2f }",
                Cliente, Tiempo_de_almacenamiento, Cantidad_de_cursos, Costo_por_almacenamiento, Costo_de_soporte, Cantidad_de_operadores, Costo_por_gestion, Cotizacion
            );

            try (OutputStream os = con.getOutputStream()) {
                byte[] input = jsonInputString.getBytes("utf-8");
                os.write(input, 0, input.length);
            }

            int responseCode = con.getResponseCode();
            historialAreaIT.cargarFilasDesdeDirectus();
        } catch (Exception e) {
            
        }
    }

    public static String generarToken() {
        try {

            URL url = new URL("http://localhost:8055/auth/login");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("POST");
            con.setRequestProperty("Content-Type", "application/json");
            con.setDoOutput(true);

            String jsonInputString = "{"
                    + "\"email\": \"brmayoralg@gmail.com\","
                    + "\"password\": \"123\""
                    + "}";

            try (OutputStream os = con.getOutputStream()) {
                os.write(jsonInputString.getBytes(StandardCharsets.UTF_8));
            }

            
            int responseCode = con.getResponseCode();
            if (responseCode == HttpURLConnection.HTTP_OK) {
                StringBuilder response = new StringBuilder();
                try (BufferedReader in = new BufferedReader(
                        new InputStreamReader(con.getInputStream(), StandardCharsets.UTF_8))) {
                    String line;
                    while ((line = in.readLine()) != null) {
                        response.append(line);
                    }
                }

                // 5. Extraer el access_token con regex
                String responseBody = response.toString();
                Pattern pattern = Pattern.compile("\"access_token\"\\s*:\\s*\"([^\"]+)\"");
                Matcher matcher = pattern.matcher(responseBody);
                if (matcher.find()) {
                    String accessToken = matcher.group(1);
                    return accessToken; // Regresa el token
                } else {

                    return null;
                }

            } else {

                return null;
            }

        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    public static void AclararCampos(){
        for(JTextField obj:ListaText){
            obj.setBackground(Color.white);
        }
    }
    
    
    public static boolean validarCampoVacio(){
        AclararCampos();
        boolean x=false;
        for(JTextField obj:ListaText){
            if(obj.getText().trim().isEmpty()){
                obj.setBackground(Color.red);
                x=true;
            }
        }
        return x;
    }
    
    public static boolean validarCaracter(){
        AclararCampos();
        boolean x=false;
        
        for(JTextField obj:ListaText){
            try{
                int a=Integer.parseInt(obj.getText().trim());
            }catch(Exception e){
                x=true;
                obj.setBackground(Color.red);
            }
        }
        
        return x;
    }
    
    public static boolean validarNegativo(){
        AclararCampos();
        boolean x=false;
        
        for(JTextField obj:ListaText){
            int a=Integer.parseInt(obj.getText().trim());
            if(a<0){
                obj.setBackground(Color.red);
                x=true;
            }
        }
        return x;
    }
    
    public void Design(){
        getContentPane().setBackground(new Color(214,217,223)); 
        lblFranja.setOpaque(true);
        lblFranja.setBackground(new Color(35, 45, 60)); 
        lblTitle.setFont(new Font("Arial", Font.BOLD, 30));
        lblCliente.setFont(new Font("Arial", Font.BOLD, 15));
        lblTiempoAl.setFont(new Font("Arial", Font.BOLD, 15));
        lblCantidadCursos.setFont(new Font("Arial", Font.BOLD, 15));
        lblCantidadOP.setFont(new Font("Arial", Font.BOLD, 15));
    }

    public JPanel getJpCotizacionIT() {
        return jpCotizacionIT;
    }

    
    private javax.swing.JPanel jpNuevaCotizacion;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jpCotizacionIT;
    private javax.swing.JLabel lblCantidadCursos;
    private javax.swing.JLabel lblCantidadOP;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFranja;
    private javax.swing.JLabel lblTiempoAl;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCC;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtOP;
    private javax.swing.JTextField txtTA;
    // End of variables declaration//GEN-END:variables
}
