/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AreaIT;

import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import org.jdatepicker.impl.JDatePanelImpl;
import java.util.Properties;
import static AreaIT.CotizacionIT.AclararCampos;
import static AreaIT.CotizacionIT.ListaText;
import static AreaIT.CotizacionIT.generarToken;
import CotizadorPlai.Editar;
import java.awt.Color;
import java.awt.Cursor;
import CotizadorPlai.HistorialCotizacion;
import CotizadorPlai.Main;
import CotizadorPlai.NuevaCotizacion;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;


/**
 *
 * @author brmay
 */
public class historialAreaIT extends javax.swing.JFrame {
    HistorialCotizacion historial;
    /**
     * Creates new form historialAreaIT
     */
    public historialAreaIT(HistorialCotizacion historial) {
        this.historial=historial;
        this.jphistorial=historial.getJpHistorialCotizacion();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        lblFranja.setOpaque(true);
        lblFranja.setBackground(new Color(35, 45, 60));
        Design();
        inicializarYFiltrarHistorial();
        cargarFilasDesdeDirectus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFranja = new javax.swing.JLabel();
        jphistorialAreaIT = new javax.swing.JPanel();
        lblTileHistorialAreaIT = new javax.swing.JLabel();
        lblClienteHistorialAreaIT = new javax.swing.JLabel();
        txtClienteHistorialAreaIT = new javax.swing.JTextField();
        lblFechaHistorialAreaIT = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCotizacionesAreaIT = new javax.swing.JTable();
        btnBuscarHistorialAreaIT = new javax.swing.JButton();
        btnVolverHistorialAreaIt = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 541));
        getContentPane().setLayout(null);
        getContentPane().add(lblFranja);
        lblFranja.setBounds(84, 0, 690, 52);

        jphistorialAreaIT.setLayout(null);

        lblTileHistorialAreaIT.setText("Historial de cotizaciones Plai");
        jphistorialAreaIT.add(lblTileHistorialAreaIT);
        lblTileHistorialAreaIT.setBounds(210, 60, 530, 50);

        lblClienteHistorialAreaIT.setText("Cliente:");
        jphistorialAreaIT.add(lblClienteHistorialAreaIT);
        lblClienteHistorialAreaIT.setBounds(10, 100, 70, 16);

        txtClienteHistorialAreaIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteHistorialAreaITActionPerformed(evt);
            }
        });
        jphistorialAreaIT.add(txtClienteHistorialAreaIT);
        txtClienteHistorialAreaIT.setBounds(90, 100, 85, 22);

        lblFechaHistorialAreaIT.setText("Fecha:");
        jphistorialAreaIT.add(lblFechaHistorialAreaIT);
        lblFechaHistorialAreaIT.setBounds(10, 130, 80, 16);

        jtCotizacionesAreaIT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Costo almc", "Costo soporte tec", "Tiempo almacenamiento", "Cantidad operadores", "Costo Moodle", "Cotizacion", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtCotizacionesAreaIT);

        jphistorialAreaIT.add(jScrollPane1);
        jScrollPane1.setBounds(10, 190, 762, 298);

        btnBuscarHistorialAreaIT.setText("Buscar");
        btnBuscarHistorialAreaIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHistorialAreaITActionPerformed(evt);
            }
        });
        jphistorialAreaIT.add(btnBuscarHistorialAreaIT);
        btnBuscarHistorialAreaIT.setBounds(10, 160, 72, 23);

        btnVolverHistorialAreaIt.setText("Volver");
        btnVolverHistorialAreaIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverHistorialAreaItActionPerformed(evt);
            }
        });
        jphistorialAreaIT.add(btnVolverHistorialAreaIt);
        btnVolverHistorialAreaIt.setBounds(10, 60, 72, 23);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jphistorialAreaIT.add(btnLimpiar);
        btnLimpiar.setBounds(100, 160, 72, 23);

        getContentPane().add(jphistorialAreaIT);
        jphistorialAreaIT.setBounds(0, 0, 830, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarHistorialAreaITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHistorialAreaITActionPerformed
        btnBuscarHistorialAreaIT.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
       cargarFilasDesdeDirectus();
    }//GEN-LAST:event_btnBuscarHistorialAreaITActionPerformed

    private void btnVolverHistorialAreaItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverHistorialAreaItActionPerformed
        jphistorialAreaIT.setVisible(false);
        jphistorial.setVisible(true);
        btnVolverHistorialAreaIt.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
    }//GEN-LAST:event_btnVolverHistorialAreaItActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
        btnLimpiar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        txtClienteHistorialAreaIT.setText("");
        datePicker.getModel().setValue(null);
        AclararCampos();
        cargarFilasDesdeDirectus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtClienteHistorialAreaITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteHistorialAreaITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteHistorialAreaITActionPerformed

    /**
     * @param args the command line arguments
     */
    public JPanel getJphistorialAreaIT() {
        return jphistorialAreaIT;
    }
    
    public void Design(){
        lblTileHistorialAreaIT.setFont(new Font("Arial", Font.BOLD, 30));
        lblClienteHistorialAreaIT.setFont(new Font("Arial", Font.BOLD, 15));
        lblFechaHistorialAreaIT.setFont(new Font("Arial", Font.BOLD, 15));
    }
    
    public void cargarFilasDesdeDirectus() {
        try {
            String urlStr = "http://localhost:8055/items/Cotizador_IT";
            String token = generarToken();
            HttpURLConnection conn = (HttpURLConnection) new URL(urlStr).openConnection();
            conn.setRequestMethod("GET");
            conn.setRequestProperty("Authorization", "Bearer " + token);

            BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            StringBuilder sb = new StringBuilder();
            String linea;
            while ((linea = reader.readLine()) != null) sb.append(linea);
            reader.close();

            // Parsear usando JSON.simple
            JSONParser parser = new JSONParser();
            JSONObject jsonResponse = (JSONObject) parser.parse(sb.toString());

            if (!jsonResponse.containsKey("data")) {
                throw new IllegalStateException("No se encontró el array 'data' en la respuesta.");
            }

            JSONArray dataArray = (JSONArray) jsonResponse.get("data");

            DefaultTableModel model = (DefaultTableModel) jtCotizacionesAreaIT.getModel();
            model.setRowCount(0);

            String clienteFiltro = txtClienteHistorialAreaIT.getText().trim().toLowerCase();

            Date selectedDate = (Date) datePicker.getModel().getValue();
            String fechaFiltroStr = "";
            if (selectedDate != null) {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                fechaFiltroStr = sdf.format(selectedDate);
            }

            NumberFormat numberFormat = NumberFormat.getNumberInstance(Locale.US);
            numberFormat.setMinimumFractionDigits(2);
            numberFormat.setMaximumFractionDigits(2);

            for (Object item : dataArray) {
                JSONObject fila = (JSONObject) item;

                String nombre = String.valueOf(fila.getOrDefault("Nombre", "")).toLowerCase();
                String fecha = String.valueOf(fila.getOrDefault("Fecha", ""));

                boolean coincideCliente = clienteFiltro.isEmpty() || nombre.contains(clienteFiltro);
                boolean coincideFecha = true;

                if (!fechaFiltroStr.isEmpty() && fecha != null && !fecha.isEmpty()) {
                    try {
                        String fechaISO = fecha.split("T")[0];
                        SimpleDateFormat formatoServidor = new SimpleDateFormat("yyyy-MM-dd");
                        SimpleDateFormat formatoUsuario = new SimpleDateFormat("dd/MM/yyyy");
                        String fechaServidorFormateada = formatoUsuario.format(formatoServidor.parse(fechaISO));
                        coincideFecha = fechaServidorFormateada.equals(fechaFiltroStr);
                    } catch (Exception e) {
                        coincideFecha = false;
                    }
                }

                if (coincideCliente && coincideFecha) {
                    Object[] datos = new Object[]{
                        fila.getOrDefault("Nombre", ""),
                        formatIfNumber(fila.get("Costo_por_almacenamiento"), numberFormat),
                        formatIfNumber(fila.get("Costo_soporte_tecnico"), numberFormat),
                        fila.getOrDefault("Tiempo_de_almacenamiento", ""),
                        fila.getOrDefault("Cantidad_de_operadores", ""),
                        formatIfNumber(fila.get("Costo_moodle"), numberFormat),
                        formatIfNumber(fila.get("Cotizacion"), numberFormat),
                        fila.getOrDefault("Fecha", "")
                    };
                    model.addRow(datos);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(jtCotizacionesAreaIT, "Error al cargar datos: " + e.getMessage());
        }
    }
    
    private Object formatIfNumber(Object valor, NumberFormat nf) {
        if (valor == null) return "";
        try {
            if (valor instanceof Number) {
                return nf.format(((Number) valor).doubleValue());
            } else {
                return nf.format(Double.parseDouble(valor.toString()));
            }
        } catch (NumberFormatException e) {
            return valor.toString();
        }
    }


    
    public void inicializarYFiltrarHistorial() {
        // 1. Crear y agregar el JDatePicker al panel
        UtilDateModel model = new UtilDateModel();
        Properties p = new Properties();
        p.put("text.today", "Hoy");
        p.put("text.month", "Mes");
        p.put("text.year", "Año");
        JDatePanelImpl datePanel = new JDatePanelImpl(model, p);
        datePicker = new JDatePickerImpl(datePanel, new org.jdatepicker.impl.DateComponentFormatter());
        datePicker.setBounds(90, 130, 150, 25);
        jphistorialAreaIT.add(datePicker);
        jphistorialAreaIT.repaint();
    }
    
    
   
    private JDatePickerImpl datePicker;
    private javax.swing.JPanel jphistorial;
    public static Date selectedDate;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarHistorialAreaIT;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolverHistorialAreaIt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jphistorialAreaIT;
    private static javax.swing.JTable jtCotizacionesAreaIT;
    private javax.swing.JLabel lblClienteHistorialAreaIT;
    private javax.swing.JLabel lblFechaHistorialAreaIT;
    private javax.swing.JLabel lblFranja;
    private javax.swing.JLabel lblTileHistorialAreaIT;
    private static javax.swing.JTextField txtClienteHistorialAreaIT;
    // End of variables declaration//GEN-END:variables
}
