/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AreaIT;

import static AreaIT.CotizacionIT.AclararCampos;
import static AreaIT.CotizacionIT.ListaText;
import CotizadorPlai.Editar;
import java.awt.Color;
import java.awt.Cursor;
import CotizadorPlai.HistorialCotizacion;
import CotizadorPlai.Main;
import CotizadorPlai.NuevaCotizacion;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author brmay
 */
public class historialAreaIT extends javax.swing.JFrame {
    HistorialCotizacion historial;
    /**
     * Creates new form historialAreaIT
     */
    public historialAreaIT(HistorialCotizacion historial) {
        this.historial=historial;
        this.jphistorial=historial.getJpHistorialCotizacion();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        lblFranja.setOpaque(true);
        lblFranja.setBackground(new Color(35, 45, 60));
        Design();
        cargarFilasDesdeDirectus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFranja = new javax.swing.JLabel();
        jphistorialAreaIT = new javax.swing.JPanel();
        lblTileHistorialAreaIT = new javax.swing.JLabel();
        lblClienteHistorialAreaIT = new javax.swing.JLabel();
        txtClienteHistorialAreaIT = new javax.swing.JTextField();
        lblFechaHistorialAreaIT = new javax.swing.JLabel();
        jfFechaHistorialAreaIT = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCotizacionesAreaIT = new javax.swing.JTable();
        btnBuscarHistorialAreaIT = new javax.swing.JButton();
        btnVolverHistorialAreaIt = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 541));
        getContentPane().setLayout(null);
        getContentPane().add(lblFranja);
        lblFranja.setBounds(84, 0, 690, 52);

        jphistorialAreaIT.setLayout(null);

        lblTileHistorialAreaIT.setText("Historial de cotizaciones Plai");
        jphistorialAreaIT.add(lblTileHistorialAreaIT);
        lblTileHistorialAreaIT.setBounds(210, 60, 530, 50);

        lblClienteHistorialAreaIT.setText("Cliente:");
        jphistorialAreaIT.add(lblClienteHistorialAreaIT);
        lblClienteHistorialAreaIT.setBounds(10, 100, 70, 16);
        jphistorialAreaIT.add(txtClienteHistorialAreaIT);
        txtClienteHistorialAreaIT.setBounds(90, 100, 85, 22);

        lblFechaHistorialAreaIT.setText("Fecha:");
        jphistorialAreaIT.add(lblFechaHistorialAreaIT);
        lblFechaHistorialAreaIT.setBounds(10, 130, 80, 16);

        jfFechaHistorialAreaIT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jfFechaHistorialAreaIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfFechaHistorialAreaITActionPerformed(evt);
            }
        });
        jphistorialAreaIT.add(jfFechaHistorialAreaIT);
        jfFechaHistorialAreaIT.setBounds(90, 130, 85, 22);

        jtCotizacionesAreaIT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Costo almc", "Costo soporte tec", "Tiempo almacenamiento", "Cantidad operadores", "Costo Moodle", "Cotizacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtCotizacionesAreaIT);

        jphistorialAreaIT.add(jScrollPane1);
        jScrollPane1.setBounds(10, 190, 762, 298);

        btnBuscarHistorialAreaIT.setText("Buscar");
        btnBuscarHistorialAreaIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHistorialAreaITActionPerformed(evt);
            }
        });
        jphistorialAreaIT.add(btnBuscarHistorialAreaIT);
        btnBuscarHistorialAreaIT.setBounds(10, 160, 72, 23);

        btnVolverHistorialAreaIt.setText("Volver");
        btnVolverHistorialAreaIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverHistorialAreaItActionPerformed(evt);
            }
        });
        jphistorialAreaIT.add(btnVolverHistorialAreaIt);
        btnVolverHistorialAreaIt.setBounds(10, 60, 72, 23);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jphistorialAreaIT.add(btnLimpiar);
        btnLimpiar.setBounds(100, 160, 72, 23);

        getContentPane().add(jphistorialAreaIT);
        jphistorialAreaIT.setBounds(0, 0, 830, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarHistorialAreaITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHistorialAreaITActionPerformed
        btnBuscarHistorialAreaIT.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
       cargarFilasDesdeDirectus();
    }//GEN-LAST:event_btnBuscarHistorialAreaITActionPerformed

    private void btnVolverHistorialAreaItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverHistorialAreaItActionPerformed
        jphistorialAreaIT.setVisible(false);
        jphistorial.setVisible(true);
        btnVolverHistorialAreaIt.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
    }//GEN-LAST:event_btnVolverHistorialAreaItActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        btnLimpiar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        txtClienteHistorialAreaIT.setText("");
        jfFechaHistorialAreaIT.setText("");
        AclararCampos();
        cargarFilasDesdeDirectus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jfFechaHistorialAreaITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfFechaHistorialAreaITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfFechaHistorialAreaITActionPerformed

    /**
     * @param args the command line arguments
     */
    public JPanel getJphistorialAreaIT() {
        return jphistorialAreaIT;
    }
    
    public void Design(){
        lblTileHistorialAreaIT.setFont(new Font("Arial", Font.BOLD, 30));
        lblClienteHistorialAreaIT.setFont(new Font("Arial", Font.BOLD, 15));
        lblFechaHistorialAreaIT.setFont(new Font("Arial", Font.BOLD, 15));
    }
    
    public static void cargarFilasDesdeDirectus() {
        try {
            String urlStr = "http://localhost:8055/items/IT";
            // 1. Hacer la petición HTTP
            String Token = generarToken();
            HttpURLConnection conn = (HttpURLConnection) new URL(urlStr).openConnection();
            conn.setRequestMethod("GET");
            conn.setRequestProperty("Authorization", "Bearer " + Token);
            BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            StringBuilder sb = new StringBuilder();
            String linea;
            while ((linea = reader.readLine()) != null) sb.append(linea);
            reader.close();

            // 2. Extraer el array "data"
            String json = sb.toString();
            int start = json.indexOf("[");
            int end = json.lastIndexOf("]") + 1;
            if (start == -1 || end == -1) {
                throw new IllegalStateException("No se encontró el array 'data'.");
            }
            String dataArray = json.substring(start, end);

            // 3. Separar objetos JSON simples
            List<String> objetos = Arrays.asList(dataArray.split("\\},\\{"));

            // 4. Obtener modelo y columnas existentes
            DefaultTableModel model = (DefaultTableModel) jtCotizacionesAreaIT.getModel();
            int numCols = model.getColumnCount();

            // 5. Limpiar filas existentes
            model.setRowCount(0);

            // Obtener filtros
            String clienteFiltro = txtClienteHistorialAreaIT.getText().trim().toLowerCase();
            String fechaFiltroStr = jfFechaHistorialAreaIT.getText().trim();

            for (String objStr : objetos) {
                objStr = objStr.replaceAll("^\\{", "").replaceAll("\\}$", "");
                String[] pares = objStr.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)");

                Map<String, String> fila = new HashMap<>();
                for (String par : pares) {
                    String[] kv = par.split(":", 2);
                    if (kv.length < 2) continue;
                    String clave = kv[0].trim().replaceAll("^\"|\"$", "");
                    String valor = kv[1].trim().replaceAll("^\"|\"$", "");
                    fila.put(clave, valor);
                }

                String nombre = fila.getOrDefault("Nombre", "").toLowerCase();
                String fecha = fila.getOrDefault("Fecha", ""); // Cambia "Fecha" por la clave correcta de tu JSON si es otro campo

                boolean coincideCliente = clienteFiltro.isEmpty() || nombre.contains(clienteFiltro);
                boolean coincideFecha = true;

                if (!fechaFiltroStr.isEmpty() && fecha != null && !fecha.isEmpty()) {
                    try {
                        // Extraer solo fecha sin hora (asumiendo formato ISO "yyyy-MM-ddTHH:mm:ssZ" o similar)
                        String fechaISO = fecha.split("T")[0];

                        // Formatos para comparar solo día/mes/año
                        java.text.SimpleDateFormat formatoServidor = new java.text.SimpleDateFormat("yyyy-MM-dd");
                        java.text.SimpleDateFormat formatoUsuario = new java.text.SimpleDateFormat("dd/MM/yyyy");

                        // Normaliza ambas fechas al mismo formato
                        String fechaServidorFormateada = formatoUsuario.format(formatoServidor.parse(fechaISO));

                        coincideFecha = fechaServidorFormateada.equals(fechaFiltroStr);
                    } catch (Exception e) {
                        coincideFecha = false;
                    }
                }

                if (coincideCliente && coincideFecha) {
                    Object[] datos = new Object[]{
                        fila.getOrDefault("Nombre", ""),
                        fila.getOrDefault("Costo_por_almacenamiento", ""),
                        fila.getOrDefault("Costo_soporte_tecnico", ""),
                        fila.getOrDefault("Tiempo_de_almacenamiento", ""),
                        fila.getOrDefault("Cantidad_de_operadores", ""),
                        fila.getOrDefault("Costo_moodle", ""),
                        fila.getOrDefault("Cotizacion", "")
                    };
                    model.addRow(datos);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(jtCotizacionesAreaIT, "Error al cargar datos: " + e.getMessage());
        }
    }
    
    public static void AclararCampos(){
        for(JTextField obj:ListaText){
            obj.setBackground(Color.white);
        }
    }
    
    public static String generarToken() {
        try {

            URL url = new URL("http://localhost:8055/auth/login");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("POST");
            con.setRequestProperty("Content-Type", "application/json");
            con.setDoOutput(true);

            String jsonInputString = "{"
                    + "\"email\": \"brmayoralg@gmail.com\","
                    + "\"password\": \"123\""
                    + "}";

            try (OutputStream os = con.getOutputStream()) {
                os.write(jsonInputString.getBytes(StandardCharsets.UTF_8));
            }

            
            int responseCode = con.getResponseCode();
            if (responseCode == HttpURLConnection.HTTP_OK) {
                StringBuilder response = new StringBuilder();
                try (BufferedReader in = new BufferedReader(
                        new InputStreamReader(con.getInputStream(), StandardCharsets.UTF_8))) {
                    String line;
                    while ((line = in.readLine()) != null) {
                        response.append(line);
                    }
                }

                // 5. Extraer el access_token con regex
                String responseBody = response.toString();
                Pattern pattern = Pattern.compile("\"access_token\"\\s*:\\s*\"([^\"]+)\"");
                Matcher matcher = pattern.matcher(responseBody);
                if (matcher.find()) {
                    String accessToken = matcher.group(1);
                    return accessToken; // Regresa el token
                } else {

                    return null;
                }

            } else {

                return null;
            }

        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    
    
    private javax.swing.JPanel jphistorial;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarHistorialAreaIT;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolverHistorialAreaIt;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JFormattedTextField jfFechaHistorialAreaIT;
    private javax.swing.JPanel jphistorialAreaIT;
    private static javax.swing.JTable jtCotizacionesAreaIT;
    private javax.swing.JLabel lblClienteHistorialAreaIT;
    private javax.swing.JLabel lblFechaHistorialAreaIT;
    private javax.swing.JLabel lblFranja;
    private javax.swing.JLabel lblTileHistorialAreaIT;
    private static javax.swing.JTextField txtClienteHistorialAreaIT;
    // End of variables declaration//GEN-END:variables
}
