/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package CotizadorPlai;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.text.Document;

/**
 *
 * @author brmay
 */
public class CotizacionIT extends javax.swing.JDialog {
    static float CA=580,ST=375,CGM=85;
    
    /**
     * Creates new form CotizacionIT
     */
    public CotizacionIT(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.white);
        setSize(600,570);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOP = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tiempo de almacenamiento (meses que el curso estará en plataforma):");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 266, 440, 25);
        getContentPane().add(txtTA);
        txtTA.setBounds(470, 270, 110, 22);

        jLabel2.setText(" Cantidad de Cursos:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(14, 300, 150, 16);
        getContentPane().add(txtCC);
        txtCC.setBounds(470, 300, 110, 22);

        jLabel3.setText(" Cantidad de operadores para brindar el soporte:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(14, 328, 559, 16);
        getContentPane().add(txtOP);
        txtOP.setBounds(290, 330, 116, 22);

        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setIcon(new javax.swing.ImageIcon("C:\\Users\\brmay\\OneDrive\\Escritorio\\img\\accounting_calculator_banking_currency_dollar_bank_business_money_making_icon_258655.png")); // NOI18N
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(280, 380, 90, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\brmay\\OneDrive\\Escritorio\\img\\FondoArriba.jpeg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 660, 220);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\brmay\\OneDrive\\Escritorio\\img\\FondeAbajo.jpeg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 420, 660, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try{
            float TA=Float.parseFloat(txtTA.getText());
            float CC=Float.parseFloat(txtCC.getText());
            float OP=Float.parseFloat(txtOP.getText());
           
            float Cotizacion=TA*((CC*CA)+((CC/30)*ST))+(OP*CC*CGM);
            
            JOptionPane.showMessageDialog(null,"La cotizacion es: "+Cotizacion);
            
            generarTicketImagen("tickect.png",TA,CC,OP,Cotizacion);
                    
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CotizacionIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CotizacionIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CotizacionIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CotizacionIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CotizacionIT dialog = new CotizacionIT(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    public static void generarTicketImagen(String nombreArchivo, float TA, float CC, float OP, float Cotizacion) {
    try {
        // Obtener el token antes de hacer la solicitud
        String token = generarToken(); // Llama a la función generarToken para obtener el token

        if (token == null || token.isEmpty()) {
            System.out.println("Error: No se pudo obtener el token.");
            return;
        }

        // Usa el token directamente en la cabecera Authorization
        URL url = new URL("http://localhost:8055/items/IT");
        HttpURLConnection con = (HttpURLConnection) url.openConnection();
        con.setRequestMethod("POST");
        con.setRequestProperty("Content-Type", "application/json");
        con.setRequestProperty("Authorization", "Bearer " + token);  // Usamos el token obtenido
        con.setDoOutput(true);

        String jsonInputString = String.format(
            "{ \"Tiempo_de_almacenamiento\": %.2f, \"Cantidad_de_cursos\": %.2f, \"Costo_por_almacenamiento\": %.2f, \"Costo_soporte_tecnico\": %.2f, \"Cantidad_de_operadores\": %.2f, \"Costo_moodle\": %.2f, \"Cotizacion\": %.2f }",
            TA, CC, CA, ST, OP, CGM, Cotizacion
        );


        try (OutputStream os = con.getOutputStream()) {
            byte[] input = jsonInputString.getBytes("utf-8");
            os.write(input, 0, input.length);
        }

        int responseCode = con.getResponseCode();
        

    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    
    
    public static String generarToken() {
    try {
        // 1. Configurar la conexión POST al endpoint de login
        URL url = new URL("http://localhost:8055/auth/login");
        HttpURLConnection con = (HttpURLConnection) url.openConnection();
        con.setRequestMethod("POST");
        con.setRequestProperty("Content-Type", "application/json");
        con.setDoOutput(true);

        // 2. JSON con tus credenciales
        String jsonInputString = "{"
            + "\"email\": \"brmayoralg@gmail.com\"," // Aquí pones tu correo
            + "\"password\": \"123\"" // Aquí pones tu contraseña
            + "}";

        // 3. Enviar credenciales
        try (OutputStream os = con.getOutputStream()) {
            os.write(jsonInputString.getBytes(StandardCharsets.UTF_8));
        }

        // 4. Leer la respuesta
        int responseCode = con.getResponseCode();
        if (responseCode == HttpURLConnection.HTTP_OK) {
            StringBuilder response = new StringBuilder();
            try (BufferedReader in = new BufferedReader(
                    new InputStreamReader(con.getInputStream(), StandardCharsets.UTF_8))) {
                String line;
                while ((line = in.readLine()) != null) {
                    response.append(line);
                }
            }

            // 5. Extraer el access_token con regex
            String responseBody = response.toString();
            Pattern pattern = Pattern.compile("\"access_token\"\\s*:\\s*\"([^\"]+)\"");
            Matcher matcher = pattern.matcher(responseBody);
            if (matcher.find()) {
                String accessToken = matcher.group(1);
                return accessToken; // Regresa el token
            } else {
                
                return null;
            }

        } else {
            
            return null;
        }

    } catch (Exception e) {
        e.printStackTrace();
        return null;
    }
}
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCC;
    private javax.swing.JTextField txtOP;
    private javax.swing.JTextField txtTA;
    // End of variables declaration//GEN-END:variables
}
