/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CotizadorPlai;


import AreaIT.CotizacionIT;
import java.awt.Color;
import java.awt.Font;
import CotizadorPlai.Main;
import java.awt.Cursor;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author brmay
 */
public class Editar extends javax.swing.JFrame {
    Main main;
    /**
     * Creates new form HistorialCotizacion
     */
    public Editar(Main main) {
        this.main=main;
        this.jpMain=main.getJpMain();
        initComponents();
        setResizable(false); 
        setLocationRelativeTo(null);
        Design();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFranja = new javax.swing.JLabel();
        jpEditar = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnAreaIt = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 541));
        getContentPane().setLayout(null);
        getContentPane().add(lblFranja);
        lblFranja.setBounds(84, 0, 595, 44);

        jpEditar.setLayout(null);

        lblTitle.setText("Editar");
        jpEditar.add(lblTitle);
        lblTitle.setBounds(40, 90, 180, 40);

        btnAreaIt.setText("Area I+T");
        btnAreaIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaItActionPerformed(evt);
            }
        });
        jpEditar.add(btnAreaIt);
        btnAreaIt.setBounds(20, 140, 154, 70);

        btnvolver.setText("volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        jpEditar.add(btnvolver);
        btnvolver.setBounds(10, 60, 72, 23);

        getContentPane().add(jpEditar);
        jpEditar.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAreaItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaItActionPerformed
        // TODO add your handling code here:
        btnvolver.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnAreaItActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        jpEditar.setVisible(false);
        jpMain.setVisible(true);
    }//GEN-LAST:event_btnvolverActionPerformed

    public static void Design(){
        lblFranja.setOpaque(true);
        lblFranja.setBackground(new Color(35, 45, 60));
        lblTitle.setFont(new Font("Arial", Font.BOLD, 30));
        btnAreaIt.setFont(new Font("Arial", Font.BOLD, 15));
        btnAreaIt.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        btnAreaIt.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * @param args the command line arguments
     */ 
    public JPanel getJpEditar() {
        return jpEditar;
    }
 
    
    
    
    private javax.swing.JPanel jpMain;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnAreaIt;
    private javax.swing.JButton btnvolver;
    private javax.swing.JPanel jpEditar;
    private static javax.swing.JLabel lblFranja;
    private static javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
