/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CotizadorPlai;

import AreaIT.historialAreaIT;
import java.awt.Color;
import java.awt.Font;
import java.awt.Component;
import java.awt.Container;
import java.awt.Cursor;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author brmay
 */
public class HistorialCotizacion extends javax.swing.JFrame {
    private Main main;
    /**
     * Creates new form HistorialCotizacion
     */
    public HistorialCotizacion(Main main) {
        this.main = main;
        this.jpMain = main.getJpMain();
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        Design(); 
        Paneles();
        main.getContentPane().add(jphistorialAreaIT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFranja = new javax.swing.JLabel();
        jpHistorialCotizacion = new javax.swing.JPanel();
        btnvolver = new javax.swing.JButton();
        btnAreaIt = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 541));
        getContentPane().setLayout(null);
        getContentPane().add(lblFranja);
        lblFranja.setBounds(0, 0, 595, 44);

        jpHistorialCotizacion.setLayout(null);

        btnvolver.setText("volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        jpHistorialCotizacion.add(btnvolver);
        btnvolver.setBounds(10, 60, 72, 23);

        btnAreaIt.setText("Area I+T");
        btnAreaIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaItActionPerformed(evt);
            }
        });
        jpHistorialCotizacion.add(btnAreaIt);
        btnAreaIt.setBounds(20, 150, 154, 70);

        lblTitle.setText("Historial Cotizaciones");
        jpHistorialCotizacion.add(lblTitle);
        lblTitle.setBounds(50, 90, 400, 50);

        getContentPane().add(jpHistorialCotizacion);
        jpHistorialCotizacion.setBounds(0, 0, 390, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAreaItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaItActionPerformed
        jpHistorialCotizacion.setVisible(false);
        jphistorialAreaIT.setVisible(true);
    }//GEN-LAST:event_btnAreaItActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        jpHistorialCotizacion.setVisible(false);
        jpMain.setVisible(true);
    }//GEN-LAST:event_btnvolverActionPerformed

    public static void Design(){
        lblFranja.setOpaque(true);
        lblFranja.setBackground(new Color(35, 45, 60));
        lblTitle.setFont(new Font("Arial", Font.BOLD, 30));
        btnAreaIt.setFont(new Font("Arial", Font.BOLD, 16));
        btnAreaIt.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        btnAreaIt.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    /**
     * @param args the command line arguments
     */
    

    public JPanel getJpHistorialCotizacion() {
        return jpHistorialCotizacion;
    }
    
    public void Paneles(){
        jphistorialAreaIT=new historialAreaIT(this).getJphistorialAreaIT();
        jphistorialAreaIT.setVisible(false);
        getContentPane().add(jphistorialAreaIT);
    }
    
    
    
    
    private javax.swing.JPanel jpMain;
    private javax.swing.JPanel jphistorialAreaIT;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnAreaIt;
    private javax.swing.JButton btnvolver;
    private static javax.swing.JPanel jpHistorialCotizacion;
    private static javax.swing.JLabel lblFranja;
    private static javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
